---

urxvt_package_name: rxvt-unicode-256color

urxvt_shared_packages:
  - xclip
  - xsel

urxvt_extensions_path: /usr/lib/urxvt/perl

urxvt_extensions:
  - https://raw.githubusercontent.com/majutsushi/urxvt-font-size/master/font-size

