---

i3_utils_bin_shared_packages:
  - alsa-utils
  - dbus
  - exiv2
  - grabc
  - i3lock
  - imagemagick
  - libnotify-bin
  - maim
  - procps
  - psmisc
  - scrot
  - slop
  - sxiv
  - x11-utils
  - xdotool
  - xsel
  - zenity

# These tools will be downloaded to /usr/local/bin
i3_utils_bin_tools:
  - system-hibernate
  - system-reboot
  - system-shutdown
  - system-suspend
  - rcalc
  - xcolorpick
  - ximage
  - xkiller
  - xlock
  - xscreenshot
  - xf86-audio
  - xf86-backlight
