---

- name: ensure dbeaver requirements are installed
  include_role:
    name: apt-meta
  vars:
    apt_packages: "{{ dbeaver_shared_packages }}"

- name: ensure dbeaver deb path exists
  file:
    path: "{{ dbeaver_deb_path | dirname }}"
    state: directory
    mode: 0755

- name: ensure dbeaver deb is downloaded
  get_url:
    url: "{{ dbeaver_deb_url }}"
    dest: "{{ dbeaver_deb_path }}"
    mode: 0644
    force: True
    timeout: 30
  register: task_result
  until: task_result is succeeded
  retries: 10
  delay: 5
  notify: install dbeaver
