---

virtualbox_package_name: virtualbox

virtualbox_exclusive_packages:
  - virtualbox-dkms
  - virtualbox-ext-pack
  - virtualbox-guest-additions-iso
  - virtualbox-guest-dkms
  - virtualbox-guest-utils
  - virtualbox-guest-x11
  - virtualbox-qt

virtualbox_shared_packages:
  - dkms
  - linux-headers-amd64
  - xmount
