---

- name: find ubuntu font directory
  find:
    path: "{{ font_path_ubuntu }}"
    pattern: '^ubuntu-font-family-[.0-9]+$'
    file_type: directory
    use_regex: yes
  register: font_ubuntu_font_dirs

- name: ensure ubuntu font directory is removed
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ font_ubuntu_font_dirs.files | default([]) }}"
  when: font_ubuntu_font_dirs.files is defined
  notify: update font-cache
