---

- name: ensure requirements are installed
  include_role:
    name: apt-meta
  vars:
    apt_packages: "{{ packer_shared_packages }}"

- name: fetch packer info
  uri:
    url: https://www.packer.io/downloads.html
    method: GET
    follow_redirects: True
    return_content: True
  register: packer_info_raw
  check_mode: False
  until: packer_info_raw is succeeded
  retries: 10
  delay: 5

- name: set packer download url
  set_fact:
    packer_zip: "{{ packer_info_raw.content | regex_search(qry) }}"
  vars:
    qry: 'https://releases.*linux_amd64\.zip'
  check_mode: False

- name: ensure packer is downloaded
  unarchive:
    src: "{{ packer_zip }}"
    dest: "{{ packer_path }}"
    remote_src: True
    mode: 0755
  become: True


###
### Add bash completion
###
- name: ensure packer bash completion is available
  template:
    src: bash-completion.j2
    dest: "{{ packer_bash_completion_path }}/packer"
    mode: 0644
  become: True
