---

i3blocks_modules_path: "{{ lookup('env','HOME') }}/.local/share/i3blocks-modules"

i3blocks_modules_packages:
  - acpi
  - bash
  - cpufrequtils
  - curl
  - i3blocks
  - iproute2
  - lm-sensors
  - procps
  - pulseaudio-utils
  - wget
  - wireless-tools
