---

- name: ensure kubectl is removed
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "{{ kubectl_path }}/kubectl"
    - "{{ kubectl_bash_completion_path }}/kubectl"
  become: yes
