---

- name: ensure docker-compose is removed
  include_role:
    name: apt-meta
  vars:
    apt_state: absent
    apt_packages: "{{ docker_compose_package_name }}"

#- name: ensure docker compose is removed
#  file:
#    state: absent
#    path: "{{ docker_compose_path }}"
#  become: yes
