---

- name: ensure requirements are installed
  include_role:
    name: apt-meta
  vars:
    apt_packages: "{{ oh_my_zsh_shared_packages }}"

- name: Clone oh-my-zsh repo
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/root/.oh-my-zsh
  become: yes

- name: Create conf folder in home directory
  file: path=/root/conf/ state=directory owner=root
  become: yes

- name: deploy .zshrc
  template: src=../files/zshrc.in dest=/root/conf/zshrc owner=root
  become: yes

- name: remove standard zshrc
  file: path=/root/.zshrc state=absent
  become: yes

- name: symlink zshrc
  file: path=/root/.zshrc src=/root/conf/zshrc state=link owner=root force=true
  become: yes

- name: Set zsh as default shell
  user: name=root shell=/bin/zsh
  become: yes
