---

- name: reset bash as default shell
  user: name=root shell=/bin/bash
  become: yes

- name: ensure requirements are removed
  include_role:
    name: apt-meta
  vars:
    apt_state: absent
    apt_packages: "{{ oh_my_zsh_shared_packages }}"

- name: remove zshrc and oh-my-zsh base path
  file: path=/root/.oh-my-zsh state=absent
  become: yes

- name: remove oh-my-zsh-conf path
  file: path=/root/conf state=absent
  become: yes

- name: remove oh-my-zsh-rc symlink
  file: path=/root/.zshrc state=absent
  become: yes

- name: remove oh-my-zsh-history file
  file: path=/root/.zsh_history state=absent
  become: yes
