---

neovim_package_name: neovim

# Required packages:
# https://neovim.io/doc/user/provider.html

neovim_shared_packages:
  - xsel

neovim_exclusive_packages:
  - lua-nvim

neovim_python2_packages:
  - python-neovim

neovim_python3_packages:
  - python3-neovim
