---

libreoffice_package_name: libreoffice6.0

libreoffice_download_url: https://www.libreoffice.org/download/download/?type=deb-x86_64&version=6.0.0&lang=en-US

libreoffice_icon_name: images_office2013.zip
libreoffice_icon_path: /opt/libreoffice6.0/share/config


libreoffice_base_config: "{{ lookup('env','HOME') }}/.config/libreoffice"
libreoffice_config_path: "{{ libreoffice_base_config }}/4/user"
