---

- name: ensure font directory exists
  file:
    path: "{{ font_terminus_font_path }}"
    state: directory
    mode: 0755
  notify: update font-cache

- name: ensure fonts are downloaded
  get_url:
    url: "{{ item }}"
    dest: "{{ font_terminus_font_path }}/{{ item | basename | replace('%20', ' ') }}"
    mode: 0644
    force: yes
  with_items:
    - "{{ font_terminus_bold_urls }}"
    - "{{ font_terminus_bold_italic_urls }}"
    - "{{ font_terminus_italic_urls }}"
    - "{{ font_terminus_regular_urls }}"
  notify: update font-cache
