---

- name: ensure i3-utils-bin are removed
  file:
    state: absent
    path: "/usr/local/bin/{{ item }}"
  become: True
  with_items:
    - "{{ i3_utils_bin_tools }}"

- name: ensure ximage desktop file is removed
  file:
    state: absent
    path: /usr/share/applications/ximage.desktop
  become: True
