---

- name: ensure sublime text repo is present
  include_role:
    name: apt-repo-meta
  vars:
    apt_repo_keys:
      - "{{ sublime_apt_key }}"
    apt_repo_repositories:
      - "{{ sublime_apt_repo }}"

- name: ensure sublime text is installed
  include_role:
    name: apt-meta
  vars:
    apt_packages:
      - sublime-text

- name: ensure sublime package directory exists
  file:
    path: "{{ sublime_package_path }}"
    state: directory
    mode: 0700

- name: ensure sublime package control is installed
  get_url:
    url: "https://packagecontrol.io/Package%20Control.sublime-package"
    dest: "{{ sublime_package_path }}/Package Control.sublime-package"
