---

###
### Custom variables
###
debian_dist: bookworm


###
### Debian apt repositories
###
apt_repo_repositories:
  # main
  - file: debian-main
    repo: "deb http://deb.debian.org/debian {{ debian_dist }} main contrib non-free"
  - file: debian-main
    repo: "deb-src http://deb.debian.org/debian {{ debian_dist }} main contrib non-free"
  # updates
  - file: debian-updates
    repo: "deb http://deb.debian.org/debian {{ debian_dist }}-updates main contrib non-free"
  - file: debian-updates
    repo: "deb-src http://deb.debian.org/debian {{ debian_dist }}-updates main contrib non-free"
  # security
  - file: debian-security
    repo: "deb http://security.debian.org/debian-security {{ debian_dist }}-security main contrib non-free"
  - file: debian-security
    repo: "deb-src http://security.debian.org/debian-security {{ debian_dist }}-security main contrib non-free"


###
### Systemd services
###
systemd_enabled: []

# https://github.com/Airblader/dotfiles-manjaro/blob/master/SETUP
systemd_disabled:
  - exim4.service
  - ModemManager.services
  - nfs-common.service
  - rpcbind.service
  - rpcbind.target
  - binfmt-support.service


###
### System Python versions
###
python_2: False
python_3: True


###
### Python pip packages (add your custom packages here)
###
pip2_packages: []
#  - awscli
#  - aws-adfs

pip3_packages: []


###
### Debian packages (add your custom packages here)
###
apt_packages:
  # ---- Base Utils ----
  - dnsutils
  - gnupg
  - gnupg-agent
  - htop
  - iw
  - keychain
  - less
  - lsb-release
  - lsof
  - man-db
  - manpages
  - moreutils
  - net-tools
  - pinentry-tty
  - pwgen
  - socat
  - tmux
  - traceroute
  - tree
  - wireless-tools
  - xxd
  # ---- Sec Tools (default) ----
#  - netcat
  - nmap
  - wireshark-gtk
  # ---- Sec Tools (wireless) ----
  - aircrack-ng
  - horst
#  - kismet
#  - kismet-plugins
  # ---- Theme tools ----
  - lxappearance
#  - qt4-qtconfig
  # ---- Fonts ----
  - fonts-arphic-ukai
  - fonts-arphic-uming
  - fonts-ipafont-gothic
  - fonts-ipafont-mincho
  - fonts-liberation
  - fonts-open-sans
  - fonts-opensymbol
  - fonts-symbola
  - ttf-mscorefonts-installer
  - ttf-wqy-zenhei
  # ---- Firmwares ----
  - intel-microcode
  - firmware-misc-nonfree
  - firmware-linux
  - firmware-iwlwifi
  # Sound
  - firmware-sof-signed
  #- firmware-crystalhd (not available in debian buster)
  # ---- Block devices ----
  - libblockdev-plugins-all
  - udisks2-btrfs
  - udisks2-lvm2
  # ---- Window Manager ----
  - arandr
  - compton
  - dunst
  - feh
  - redshift
  - redshift-gtk
  - rofi
  - xss-lock
  # ---- Office / Productivity ----
  - keepassxc
  # ---- Video ----
  - vlc
  - vlc-plugin-notify
  - vlc-plugin-samba
  - x264
  - x265
  # ---- Audio ----
  - alsa-utils
  - alsa-oss
  - blueman
  - pavucontrol
  - pulseaudio
  - pulseaudio-module-bluetooth
  - pulseaudio-utils
  # ---- Network clients ----
  - jxplorer
  - mariadb-client
  - openssh-client
  - redis-tools
  - remmina
#  - remmina-plugin-nx
  - remmina-plugin-rdp
  - remmina-plugin-vnc
#  - remmina-plugin-xdmcp
  - swaks
  # ---- Development ----
  - ack
  - ack-grep
  - binutils
  - devscripts
  - dos2unix
  - exuberant-ctags
  - jq
#  - pep8
  - php-cli
  - pylint
#  - pylint3
#  - python-pep8
  - python3-pep8
  - shellcheck
  - silversearcher-ag
  - yamllint
  # ---- chat ----
  # ---- dbus ----
  #- dbus
  #- dbus-user-session
  #- dbus-x11


###
### Select packages to install
###
### 'install': Install the package
### 'remove':  Uninstall the package
### Any other value will ignore the package (neither install nor uninstall)

autorunner:            'install'
chromium:              'install'
clipmenu:              'install'
dbeaver:               'install'
diff_highlight:        'install'
docker:                'install'
docker_compose:        'install'
ffscreencast:          'install'
firefox:               'noop'
font_font_awesome:     'install'
font_droid_sans_mono:  'install'
font_san_francisco:    'install'
font_terminus:         'install'
font_ubuntu:           'noop'
fzf:                   'noop'
gimp:                  'install'
i3:                    'install'
i3_gaps:               'noop'
i3_utils_bin:          'install'
i3_utils_systemd:      'install'
i3blocks_modules:      'install'
icon_moka:             'install'
kops:                  'install'
kubectl:               'install'
libreoffice:           'noop'
lxdm:                  'install'
neovim:                'install'
network_manager:       'install'
oh_my_zsh:             'noop'
packer:                'noop'
pinta:                 'install'
ranger:                'noop'
skype:                 'noop'
sublime:               'noop'
sxiv:                  'install'
telegram:              'install'
terraform:             'noop'
theme_arc:             'install'
thunar:                'install'
thunar_custom_actions: 'noop'
thunderbird:           'install'
timemachine:           'install'
urxvt:                 'install'
virtualbox:            'noop'
xbacklight:            'install'
xorg:                  'install'
zathura:               'install'


###
### Settings for packages
###

# ---- Chromium ----
# Only works for extensions from web store
chromium_extensions:
  # vimium
  - dbepggeogbaibhgnhhndojpepiihcmeb
  # uBlock Origin
  - cjpalhdlnbpafiamejdnhcphjbkeiagm
  # uBlock Origin Extra
  - pgdnlhfefecpicbbihgmbmffkjpaplco
  # PrivacyBadger
  - pkehgijcmpdhfbdbbnkijodmdjhbjlgp
  # Github Flavored Markdown
  - faelggnmhofdamhdegcdhhemfokkfngk

# ---- Docker ----
# 'wheezy', 'jessie', 'stretch' or 'buster'
docker_repo_dist: "bullseye"
# 'stable' or 'edge'
docker_repo_channel: stable

# ---- FZF ----
# Add sourcing ~/.fzf.bash to your normal shell config?
fzf_update_rc: True
# Enable/Disable fuzzy completion (bash & zsh)?
fzf_completion: False
# Enable/disable key bindings (CTRL-T, CTRL-R, ALT-C)?
fzf_key_bindings: False

# ---- LXDM ----
lxdm_dpi: 128
lxdm_gtk_theme: Arc-Darker
lxdm_show_user_list: False

# ---- NetworkManager ----
network_manager_nm_applet: True
network_manager_plugin_openvpn: True
network_manager_plugin_l2tp: False
network_manager_plugin_openconnect: False
network_manager_plugin_pptp: False
network_manager_plugin_ssh: False
network_manager_plugin_strongswan: False
network_manager_plugin_vpnc: False

# ---- Skype ----
# 'stable' or 'unstable'
skype_repo_channel: stable

# ---- Sublime ----
# 'stable' or 'dev'
sublime_repo_channel: stable

# ---- sxiv ----
# Make sxiv default program for pictures
sxiv_default_image_viewer: True

# ---- Thunar ----
thunar_volman_enable: True
thunar_archive_plugin_enable: True

# ---- Thunderbird ----
thunderbird_ext_apt: []
#  - lightning
#  - enigmail

thunderbird_ext_official: []
#  - https://addons.mozilla.org/en-US/thunderbird/addon/dkim-verifier/
##  - https://addons.mozilla.org/en-US/thunderbird/addon/enigmail/
#  - https://addons.mozilla.org/en-US/thunderbird/addon/gnotifier/
##  - https://addons.mozilla.org/en-US/thunderbird/addon/lightning/
#  - https://addons.mozilla.org/en-US/thunderbird/addon/provider-for-google-calendar/
#  - https://addons.mozilla.org/en-US/thunderbird/addon/x-unsent-support/

# List of urls pages in which an XPI download link can be found.
# Note: The first found XPI download url will be used
thunderbird_ext_custom: []
#  - https://github.com/ExchangeCalendar/exchangecalendar/releases

# ---- Xorg ----
# Supported values: 'amdgpu' 'ati' 'intel' 'modesetting' 'nouveau' 'nvidia' 'radeon'
xorg_gpu: modesetting
# Supported values: 'XAA' 'EXA' 'UXA' 'SNA' 'glamor'
xorg_gpu_accel_method: glamor
# Enable VDPAU_DRIVER=va_gl systemwide
xorg_gpu_vdpau_va_gl_enable: True
# 'libinput' or 'synaptics'
xorg_touchpad_enable: True
xorg_touchpad_driver: 'synaptics'


###
### Set your preferred default applications
###
xdg_mime_defaults:
  - desktop_file: Thunar.desktop
    mime_types:
      - inode/directory
  - desktop_file: chromium.desktop
    mime_types:
      - text/html
      - text/xml
      - application/xhtml_xml
      - application/x-mimearchive
      - x-scheme-handler/http
      - x-scheme-handler/https
  - desktop_file: zathura.desktop
    mime_types:
      - application/pdf
      - application/postscript
      - application/eps
      - application/x-eps
      - image/eps
      - image/x-eps
